//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace langsamu.Web.Routing.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("langsamu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of regex or type is required. A constraint must be either one or the other..
        /// </summary>
        internal static string ConstraintAttributesMissing {
            get {
                return ResourceManager.GetString("ConstraintAttributesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex and type are mutually exclusive. A constraint must be either one or the other..
        /// </summary>
        internal static string ConstraintAttributesMutex {
            get {
                return ResourceManager.GetString("ConstraintAttributesMutex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex constraints cannot have create parameters..
        /// </summary>
        internal static string ConstraintRegexParametersRedundant {
            get {
                return ResourceManager.GetString("ConstraintRegexParametersRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameters to initialise type {0}..
        /// </summary>
        internal static string IncorrectParametersForInitialisation {
            get {
                return ResourceManager.GetString("IncorrectParametersForInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler type routes must not have physical file or route type..
        /// </summary>
        internal static string RouteHandlerAttributesRedundant {
            get {
                return ResourceManager.GetString("RouteHandlerAttributesRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler type routes must have name, handler type and url..
        /// </summary>
        internal static string RouteHandlerAttributesRequired {
            get {
                return ResourceManager.GetString("RouteHandlerAttributesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore routes must not have data tokens, defaults, handler type, name, parameters, physical file or route type..
        /// </summary>
        internal static string RouteIgnoreAttributesRedundant {
            get {
                return ResourceManager.GetString("RouteIgnoreAttributesRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore routes must have url..
        /// </summary>
        internal static string RouteIgnoreAttributesRequired {
            get {
                return ResourceManager.GetString("RouteIgnoreAttributesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical file routes must not have a handler type, a route type or create parameters..
        /// </summary>
        internal static string RoutePhysicalAttributesRedundant {
            get {
                return ResourceManager.GetString("RoutePhysicalAttributesRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical file routes must have a name, a physical file path and a url..
        /// </summary>
        internal static string RoutePhysicalAttributesRequired {
            get {
                return ResourceManager.GetString("RoutePhysicalAttributesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route type routes must not have constraints, data tokens, defaults, handler type or physical file.
        /// </summary>
        internal static string RouteRouteAttributesRedundant {
            get {
                return ResourceManager.GetString("RouteRouteAttributesRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route type routes must have name and route type..
        /// </summary>
        internal static string RouteRouteAttributesRequired {
            get {
                return ResourceManager.GetString("RouteRouteAttributesRequired", resourceCulture);
            }
        }
    }
}
